/**
 * Hand-drawn pixel sprites as character grids. Each character maps to a colour in
 * SPRITE_COLORS ('.' is transparent). Rows shorter than the widest row are padded.
 */
export const SPRITES: Record<string, string[]> = {
  // ------------------------------------------------------------ food
  banhMi: [
    '................',
    '................',
    '................',
    '....oooooooo....',
    '..ooYYYYYYYYoo..',
    '.oYyyYYYYyyYYYo.',
    '.oYYYYYYYYYYYYo.',
    'olgpplkglgppklgo',
    'ogkpgllpgkpgllgo',
    '.obYYYYYYYYYYbo.',
    '..obbYYYYYYbbo..',
    '...oooooooooo...',
  ],
  caPhe: [
    '.........rr.....',
    '.........rr.....',
    '.........rr.....',
    '...oooooorroo...',
    '...owiiiirrio...',
    '...owiinnrrno...',
    '...onnnnnrrno...',
    '...onniinrrno...',
    '...onnnnnnnno...',
    '...oNnnnnnnNo...',
    '...occcccccco...',
    '...occcccccco...',
    '....oooooooo....',
  ],
  flan: [
    '................',
    '................',
    '................',
    '................',
    '.....oooooo.....',
    '....oNNnnNNo....',
    '...onKKKKKKno...',
    '...oyKyyKyyyo...',
    '...oyyyyyyyyo...',
    '...oyyyyyyyYo...',
    '..oeeeeeeeeeeo..',
    '...oooooooooo...',
  ],
  pateChaud: [
    '................',
    '................',
    '................',
    '................',
    '....oooooooo....',
    '...oyYYYyYYYo...',
    '..oyYYyYYYYyYo..',
    '..oYYYYYYYYYYo..',
    '..obYbYYbYYbYo..',
    '..oYYYYYYYYYYo..',
    '...obbbbbbbbo...',
    '....oooooooo....',
  ],
  traTac: [
    '................',
    '..........kk....',
    '.........kKKk...',
    '...ooooookKko...',
    '...oiiiiiiiio...',
    '...olillilllo...',
    '...ollkklllio...',
    '...ollkKliilo...',
    '...olllllillo...',
    '...ogllllllgo...',
    '...oggllllggo...',
    '...oggggggggo...',
    '....oooooooo....',
  ],
  banhChuoi: [
    '................',
    '................',
    '................',
    '................',
    '..oooooooooooo..',
    '..oNbNbbNbNbbo..',
    '..oyKyyKyKyyKo..',
    '..oKKyKKKKyKKo..',
    '..oKyyKKyKKKyo..',
    '..oKKKKyKKKKKo..',
    '..obbbbbbbbbbo..',
    '..oooooooooooo..',
  ],
  banhBo: [
    '................',
    '................',
    '................',
    '................',
    '...oooooooooo...',
    '..oYYYYYYYYYYo..',
    '..olGllGlllGlo..',
    '..ollGllGlGllo..',
    '..oGllllGlllGo..',
    '..ollGllllGllo..',
    '..oYYYYYYYYYYo..',
    '...oooooooooo...',
  ],
  banhKem: [
    '................',
    '...g...g...g....',
    '..opo.opo.opo...',
    '..oooooooooooo..',
    '..owpwwpwwpwwo..',
    '..owwwwwwwwwwo..',
    '..oyyyyyyyyyyo..',
    '..oppppppppppo..',
    '..oyyyyyyyyyyo..',
    '..owwwwwwwwwwo..',
    '.oeeeeeeeeeeeeo.',
    '..oooooooooooo..',
  ],
  mutDua: [
    '................',
    '.....yy..yy.....',
    '......yyyy......',
    '..ooooooyyoooo..',
    '..orrrryyrrrro..',
    '..oRrrryyrrrRo..',
    '..oyyyyyyyyyyo..',
    '..orrrryyrrrro..',
    '..orrrryyrrrro..',
    '..oRRRRyyRRRRo..',
    '..oooooooooooo..',
  ],
  baguette: [
    '................',
    '................',
    '................',
    '................',
    '...ooooooooo....',
    '.ooYyYYyYYyYoo..',
    'oYYbYYYbYYYbYYo.',
    'oYYYYYYYYYYYYYo.',
    '.obbYYYYYYYbbo..',
    '..oooooooooooo..',
  ],
  // ------------------------------------------------------------ pantry
  flour: [
    '.....oo..oo.....',
    '......oooo......',
    '.....owwwwo.....',
    '....owwwwwwo....',
    '...owwwwwwwwo...',
    '...owwGGGGwwo...',
    '...owwGwwGwwo...',
    '...owwGGGGwwo...',
    '...owwwwwwwwo...',
    '...oeeeeeeeeo...',
    '....oooooooo....',
  ],
  riceFlour: [
    '.....oo..oo.....',
    '......oooo......',
    '.....owwwwo.....',
    '....owwwwwwo....',
    '...owwwwwwwwo...',
    '...owwppppwwo...',
    '...owwpwwpwwo...',
    '...owwppppwwo...',
    '...owwwwwwwwo...',
    '...oeeeeeeeeo...',
    '....oooooooo....',
  ],
  eggs: [
    '................',
    '....oooo........',
    '...occcco.oooo..',
    '..occwcccooccco.',
    '..ocwccccocwccco',
    '..occcccPoccccPo',
    '..occcccPoccccPo',
    '...occcPo.occPo.',
    '..ooooooooooooo.',
    '..oKbKbKbKbKbKo.',
    '...oooooooooooo.',
  ],
  milk: [
    '......oooo......',
    '......oeeo......',
    '.....oiiiio.....',
    '....owwwwwwo....',
    '....owwwwwwo....',
    '....otttttto....',
    '....otwwwwto....',
    '....otttttto....',
    '....owwwwwwo....',
    '....owwwwwwo....',
    '.....oooooo.....',
  ],
  condensed: [
    '................',
    '.....oooooo.....',
    '....oeeeeeeo....',
    '....oEEEEEEo....',
    '....orrrrrro....',
    '....owwwwwwo....',
    '....owrwwrwo....',
    '....owwwwwwo....',
    '....orrrrrro....',
    '....oEEEEEEo....',
    '.....oooooo.....',
  ],
  sugar: [
    '................',
    '....oooooooo....',
    '...owwwwwwwwo...',
    '...owwiwwwiwo...',
    '...owwwwwiwwo...',
    '...otttttttto...',
    '...otwwwwwwto...',
    '...otttttttto...',
    '...owwwwwwwwo...',
    '....oooooooo....',
  ],
  butter: [
    '................',
    '................',
    '.....oooooooo...',
    '....oyyyyyyyyo..',
    '...oyyyyyyyyyo..',
    '..oyyyyyyyyyYo..',
    '..oyyyyyyyyYYo..',
    '..oYYYYYYYYYo...',
    '..ooooooooooo...',
  ],
  coffee: [
    '................',
    '....oooooooo....',
    '...onnnnnnnno...',
    '...oNNNNNNNNo...',
    '...onnnnnnnno...',
    '...onycccyyno...',
    '...onyNNNNyno...',
    '...onycccyyno...',
    '...onnnnnnnno...',
    '...oNNNNNNNNo...',
    '....oooooooo....',
  ],
  chaLua: [
    '................',
    '................',
    '..g.oooooooo.g..',
    '..gogggggggggg..',
    '..ogGgggggGggo..',
    '.oggggggggggggo.',
    '.ogggppppppgggo.',
    '.oggpPPPPPPpggo.',
    '.ogggppppppgggo.',
    '..ogggggggggo...',
    '...ooooooooo....',
  ],
  veg: [
    '.....g...g......',
    '....glg.glg.....',
    '.....g.g.g......',
    '......ooo.......',
    '...okkko.owwo...',
    '..okKkkoowwwwo..',
    '..okkkKoowwwwo..',
    '...okkkoowwwo...',
    '....okko.owwo...',
    '.....oo...oo....',
  ],
  banana: [
    '................',
    '.........oo.....',
    '........oGo.....',
    '.......oyo......',
    '.....ooyyo......',
    '...ooyyyyo..o...',
    '..oyyyyyyoooyo..',
    '.oyyyyyyyyyyyo..',
    '.oyYyyyyyyyyo...',
    '..ooYYYYYYoo....',
    '....oooooo......',
  ],
  coconut: [
    '................',
    '.....oooooo.....',
    '....onnnnnno....',
    '...onNnnnnNno...',
    '..onnwwwwwwnno..',
    '..onwwwwwwwwno..',
    '..onwwwwwwwwno..',
    '..onnwwwwwwnno..',
    '...onnnnnnnno...',
    '....oooooooo....',
  ],
  kumquat: [
    '................',
    '......g.........',
    '.....glg........',
    '....okkko.okkko.',
    '...okkkkKookkkKo',
    '...okkwkKookwkKo',
    '...okkkKKookkKKo',
    '....oKKKo.oKKKo.',
    '.....ooo...ooo..',
  ],
  cream: [
    '................',
    '......p..p......',
    '.....pgppgp.....',
    '...oowwwwwwoo...',
    '..owwwwwwwwwwo..',
    '..oeeeeeeeeeeo..',
    '...otttttttto...',
    '....oTttttto....',
    '.....oooooo.....',
  ],
  // ------------------------------------------------------------ scene props
  moto: [
    '.......ooo........',
    '......oGGGo.......',
    '......oPPPo.......',
    '.....otttto.......',
    '....otttttoo.ooo..',
    '..oooootoooooorro.',
    '.orrrrrrrrrrrrrro.',
    'oooo.oooooooo.oooo',
    'oEEo.........oEEo.',
    'oeeo.........oeeo.',
    '.oo...........oo..',
  ],
  motoFlowers: [
    '..p.y.p.ooo.......',
    '.pypyppoGGGo......',
    '.ogggggoPPPo......',
    '.oYYYYotttto......',
    '.oYYYYottttoo.ooo.',
    '..oooootoooooorro.',
    '.orrrrrrrrrrrrrro.',
    'oooo.oooooooo.oooo',
    'oEEo.........oEEo.',
    'oeeo.........oeeo.',
    '.oo...........oo..',
  ],
  plant: [
    '....g..g....',
    '..gglgglgg..',
    '.gGglggGglg.',
    'glgGgggglGgg',
    '.gggGggGggg.',
    '..gg.gg.gg..',
    '.....GG.....',
    '...oooooo...',
    '...oKKKKo...',
    '...okkkko...',
    '....okko....',
    '....oooo....',
  ],
  hoaMai: [
    '..y..y.y..y.',
    '.yyy.Ny.yyy.',
    '..yN.N.yNy..',
    '.y.NyNNyN.y.',
    'yyy.NNN.yyy.',
    '.y...N...y..',
    '.....N......',
    '...oooooo...',
    '...orrrro...',
    '...oryyro...',
    '....orro....',
    '....oooo....',
  ],
  lantern: ['...o...', '..ooo..', '.orrro.', 'orryrro', 'orrrrro', 'orryrro', '.orrro.', '..oyo..', '...y...', '..y.y..'],
  lanternY: ['...o...', '..ooo..', '.oyyyo.', 'oyyryyo', 'oyyyyyo', 'oyyryyo', '.oyyyo.', '..oro..', '...r...', '..r.r..'],
  birdcage: ['....o....', '...ooo...', '..oYoYo..', '.oY.Y.Yo.', 'oY.ky..Yo', 'oY.kk..Yo', 'oY.....Yo', 'oYYYYYYYo', '.ooooooo.'],
  fan: ['oooooooooooooooo', '......oooo......', '.......oo.......'],
  // ------------------------------------------------------------ icons
  ice: ['.oooo....', 'oiiwio...', 'oiiiiooo.', 'oiiiioiwo', '.oooooiio', '....oiiio', '.....oooo'],
  chili: ['......go', '.....gg.', '...ooo..', '..orro..', '.orrro..', 'orrro...', 'oRo.....', 'oo......'],
  tea: ['...l.l...', '..oooooo.', '.olllllo.', 'ollllllooo', 'olllllo.o', 'ollllllooo', '.ooooo...'],
  spoon: ['......oo', '.....oeo', '....oeo.', '...oeo..', '..oeo...', '.oeo....', 'oeo.....', 'oo......'],
  knife: ['.......o', '......oe', '.....oeo', '....oeo.', '...oeo..', '..ono...', '.ono....', 'ono.....'],
  book: ['oooooooo', 'orrroggo', 'orwroglo', 'orrroggo', 'orwroglo', 'orrroggo', 'oooooooo'],
  gear: ['..o..o..', '.oooooo.', 'ooEEEEoo', '.oEooEo.', '.oEooEo.', 'ooEEEEoo', '.oooooo.', '..o..o..'],
  note: ['...ooo..', '...oyyo.', '...o.oo.', '...o....', '.ooo....', 'oyyo....', 'oyyo....', '.oo.....'],
  pause: ['oo..oo..', 'oo..oo..', 'oo..oo..', 'oo..oo..', 'oo..oo..', 'oo..oo..'],
  playIcon: ['o.......', 'ooo.....', 'ooooo...', 'ooooooo.', 'ooooo...', 'ooo.....', 'o.......'],
  fast: ['o...o...', 'oo..oo..', 'ooo.ooo.', 'oooooooo', 'ooo.ooo.', 'oo..oo..', 'o...o...'],
  coin: ['..oooo..', '.oyyyyo.', 'oyywyyYo', 'oyyYyyYo', 'oyyYyyYo', 'oyyyyYYo', '.oYYYYo.', '..oooo..'],
  heart: ['.oo..oo.', 'orroorro', 'orwrrrro', 'orrrrrro', '.orrrro.', '..orro..', '...oo...'],
  star: ['...oo...', '...oyo..', 'ooooyooo', 'oyyyyyyo', '.oyyyyo.', '.oyooyo.', 'oyo..oyo', 'oo....oo'],
  leaf: ['.....ooo', '...oollo', '..ollgGo', '.olgggGo', '.oggGGo.', 'oGGGoo..', 'oGoo....', 'oo......'],
  sun: ['..y..y..', 'y.oooo.y', '.oyyyyo.', '.oyyyyo.', 'yoyyyyoy', '.oyyyyo.', 'y.oooo.y', '..y..y..'],
  cloud: ['........', '..ooo...', '.owwwoo.', 'owwwwwwo', 'owwwwwwo', '.oeeeeo.', '..oooo..'],
  rain: ['..ooo...', '.oeeeoo.', 'oeeeeeeo', '.oEEEEo.', '..oooo..', '.i..i..i', 'i..i..i.'],
  hot: ['...oo...', '..okko..', '..okko..', '..okko..', '..orro..', '.orrrro.', '.orrrro.', '..oooo..'],
  cool: ['........', 'oooooo..', '.....io.', 'ooooooio', '......o.', 'ooooo...', '....io..', '.oooo...'],
  bag: ['..oooo..', '.o....o.', 'oooooooo', 'oYYYYYYo', 'oYYgGYYo', 'oYYYYYYo', 'oYYYYYYo', 'oooooooo'],
  clock: ['..oooo..', '.owwwwo.', 'owwowwwo', 'owwowwwo', 'owwoooww', 'owwwwwwo', '.owwwwo.', '..oooo..'],
  chart: ['.......o', '......oo', 'o....oGo', 'oo..oGGo', 'oGooGGGo', 'oGGGGGGo', 'oooooooo'],
  house: ['...oo...', '..orro..', '.orrrro.', 'orrrrrro', '.oyyyyo.', '.oyonyo.', '.oyonyo.', '.oooooo.'],
  crown: ['o..o..o.', 'oyoyoyo.', 'oyyyyyo.', 'oyrygyo.', 'oyyyyyo.', 'ooooooo.'],
  bell: ['...oo...', '..oyyo..', '.oyyyyo.', '.oyyyyo.', 'oyyyyyyo', 'oooooooo', '...oo...'],
  box: ['oooooooo', 'oYYbbYYo', 'oooooooo', 'oYYbbYYo', 'oYYbbYYo', 'oYYYYYYo', 'oooooooo'],
  phone: ['.oooooo.', '.oGGGGo.', '.oiiiio.', '.oiiiio.', '.oiiiio.', '.oGGGGo.', '.oGwwGo.', '.oooooo.'],
  shop: ['oooooooo', 'orwrwrwo', 'oooooooo', 'oeeeeeeo', 'oeiiiNeo', 'oeiiiNeo', 'oooooooo'],
  fridge: ['.oooooo.', '.oeeeeo.', '.oeeeoo.', '.oooooo.', '.oeeeeo.', '.oeeeoo.', '.oeeeeo.', '.oooooo.'],
  fruit: ['....g...', '...gg...', '.ooooo..', 'orrrwro.', 'orrrrro.', 'orrrrro.', '.orrro..', '..ooo...'],
  party: ['r..y..g.', '.r.y.g..', '..oooo..', '.oyyyyo.', 'oyrygryo', 'oyyyyyyo', '.oyyyyo.', '..oooo..'],
  cafe: ['..y.y...', '...y.y..', 'oooooo..', 'owwwwoo.', 'owwwwo.o', 'owwwwoo.', '.oooo...', 'oooooo..'],
  tet: ['...oo...', '..orro..', '.orrrro.', 'oryyyyro', 'orrrrrro', '.orrrro.', '..oyyo..', '...yy...'],
  sale: ['oooooo..', 'oyyyyyo.', 'oyoyyyyo', 'oyyyyyyo', 'oyyyyyo.', 'oyyyyo..', 'ooooo...'],
  egg: ['..oooo..', '.occcco.', 'occwccco', 'occcccco', 'occcccPo', '.occcPo.', '..oooo..'],
  check: ['.......o', '......og', 'o....ogo', 'go..ogo.', '.googo..', '..ggo...', '...o....'],
  lock: ['..oooo..', '.o....o.', '.o....o.', 'oooooooo', 'oyyyyyyo', 'oyyoyyyo', 'oyyoyyyo', 'oooooooo'],
  spark: ['...y....', '...y....', '.yywyy..', '...y....', '...y....'],
  people: ['.oo..oo.', 'oPPooPPo', 'oPPooPPo', '.oo..oo.', 'otto.oro', 'otttorro', 'otttorro', 'oooooooo'],
  trash: ['.oooooo.', 'oEEEEEEo', '.oeeeeo.', '.oeEeEo.', '.oeEeEo.', '.oeEeEo.', '.oeeeeo.', '..oooo..'],
  gift: ['..y..y..', '...yy...', 'ooooyooo', 'orrryrro', 'oyyyyyyo', 'orrryrro', 'orrryrro', 'oooooooo'],
};

export type SpriteName = keyof typeof SPRITES;
